version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: door_unlocker_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    command: sh -c "npx prisma migrate deploy && npm run build && npm run start"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/door_unlocker_db
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  db_data:
